" vim:tw=80:sw=4:et:sta
vim9script

syntax          on
filetype indent on
filetype plugin on

# --------------------------------- OPTIONS ------------------------------------
v:clipproviders['wl'] = {
    copy:  {'+': (_, __, lines) => system('wl-copy', lines)},
    paste: {'+': (_) => ['', systemlist('wl-paste')]},
}

se clipmethod^=wl clipboard=unnamed
se cul nu rnu scl=yes
se hidden
se ignorecase smartcase incsearch hlsearch
se list listchars=tab:»\ ,trail:·,nbsp:␣,precedes:<,extends:>
se mouse=a ttymouse=sgr                  # tmux-ready (SGR) mouse in [a]ll modes
se nf=bin,hex
se scrolloff=8 sidescrolloff=8 nowrap
se spelllang=en_gb
se splitright splitbelow splitkeep=screen fillchars=vert:\ 
se timeoutlen=320 ttimeoutlen=0
se undofile undodir=$XDG_CACHE_HOME/vim/undo
se wildoptions=pum

if executable('rg') | se grepprg=rg\ --vimgrep | endif

# -------------------------------- HIGHLIGHTS ----------------------------------
color catppuccin
const ansi = {
  dark:  ['#45475a', '#f38ba8', '#a6e3a1', '#f9e2af', '#89b4fa', '#f5c2e7', '#94e2d5', '#a6adc8', '#585b70', '#f37799', '#89d88b', '#ebd391', '#74a8fc', '#f2aede', '#6bd7ca', '#bac2de'],
  light: ['#5c5f77', '#d20f39', '#40a02b', '#df8e1d', '#1e66f5', '#ea76cb', '#179299', '#acb0be', '#6c6f85', '#de293e', '#49af3d', '#eea02d', '#456eff', '#fe85d8', '#2d9fa8', '#bcc0cc']
}
se termguicolors t_RB=]11;?
au ColorScheme * g:terminal_ansi_colors = ansi[&background]
au ColorScheme * hi! default link ColorColumn  CursorLine
au ColorScheme * hi! default link CursorColumn CursorLine
                 hi! default link GitGutterAdd    Added
                 hi! default link GitGutterChange Changed
                 hi! default link GitGutterDelete Removed

# --------------------------------- MAPPINGS -----------------------------------
g:mapleader = ' '
nno <Leader>ve :exe &l:ve == 'all' ? 'setl ve< cuc<' : 'setl ve=all cuc'
vno <Leader>ve :exe &l:ve == 'all' ? 'setl ve< cuc<' : 'setl ve=all cuc'gv
nno <Leader>b :exe &bg == 'light' ? 'se bg=dark' : 'se bg=light'
nno <Leader>x :
nno  mz:tabe %`zzz
nno <silent>  :nohl:lcl:ccl:pc
nno j :cnex:cc
nno k :cpre:cc
nno h :cold:cc
nno l :cnew:cc
cno j <Down>
cno k <Up>
nno Y y$
com W w

# ------------------------------ LOCAL HELPERS ---------------------------------
au InsertLeave kr100 silent norm! ^"=strftime("%F  ")Pw"ayiwE"byiw$"=printf("  %.1f", 100/(a+b/60.0))p
au FileType asciidoc,gitcommit,markdown setl spell
au FileType gitcommit                   setl cc=50

# --------------------------------- PLUG-INS -----------------------------------
pa! comment
pa! hlyank | g:hlput_enable = true | g:hlyank_duration = 100 | g:hlput_duration = 100 | g:hlput_hlgroup = 'Search' | g:hlyank_hlgroup = 'Search'
ru ftplugin/man.vim
ru macros/matchit.vim
