baseMouseSpeed: 512.0
baseScrollSpeed: 16.0

layers:
  - name: initial
    bindings:
      tab: tap-hold-next tab ; toggle-layer mouse ; 300
      rightalt: tap-hold-next rightalt ; toggle-layer mouse-alt ; 300

  - name: mouse-alt
    passThrough: true
    bindings:
      leftshift: speed 2
      leftctrl: speed 0.25

      r: reload-config

      a: move -1  0
      s: move  0  1
      w: move  0 -1
      d: move  1  0

      y: scroll left
      u: scroll down
      i: scroll up
      o: scroll right

      j: button left
      k: button middle
      l: button right

  - name: mouse
    passThrough: true
    bindings:
      leftctrl: tap-hold-next leftctrl ; toggle-layer arrows ; 0
      leftshift: tap-hold-next leftshift ; toggle-layer wheel ; 0

      r: reload-config

      h: move -1  0
      j: move  0  1
      k: move  0 -1
      l: move  1  0

      y: scroll left
      u: scroll down
      i: scroll up
      o: scroll right

      space: speed 0.32

      f: button left
      d: button middle
      s: button right

  - name: arrows
    bindings:
      h: left
      j: down
      k: up
      l: right

  - name: wheel
    bindings:
      h: scroll left
      j: scroll down
      k: scroll up
      l: scroll right
