"support"                                          = "blue"                                # [[, let...
"punctuation.terminator"                           = "blue"                                # terminators (e.g. ";;" after a case item)
"dynamic.callable"                                 = "green"
"string"                                           = "green"
"support.function"                                 = "magenta"                             # let, alias...
"storage.modifier"                                 = "magenta"                             # readonly, local
"keyword"                                          = "magenta"                             # repeat, while, case, if...
"dynamic.callable.missing"                         = "red"
"variable.other.readwrite"                         = "yellow"                              # left-hand in assignments
"meta.group.expansion.parameter"                   = "yellow"                              # variables
"comment"                                          = 8
"dynamic.path"                                     = { bold = true }
"variable.language.tilde"                          = { bold = true }
"variable.parameter"                               = { bold = true }                       # flags
"keyword.operator"                                 = { bold = true }                       # ||, &&, >, ;, =
"keyword.operator.assignment.redirection"          = { bold = true, foreground = "blue"  } # >, <, <>, <<, <<<
"constant.numeric.integer.decimal.file-descriptor" = { bold = true, foreground = "blue" }  # numeric file descriptors
"dynamic.callable.builtin"                         = { bold = true, foreground = "green" }
"keyword.operator.regexp"                          = { bold = true, underline = true }     # asterisk in glob, in case...
"meta.group.expansion.history.shell"               = { bold = true, underline = true }     # history expansion
"meta.group.expansion.command.parens"              = {}                                    # reset command substitution base style $()
