# Variety
# -------
"comment" = 8
"string"  = "green"

# Built-ins
# ---------
"keyword"            = "magenta"  # repeat, for, while, case, if...
"storage.modifier"   = "magenta"  # readonly, local
"support.function"   = "magenta"  # let, alias...

# Variables
# ---------
"keyword.operator.assignment.shell"    = { bold = true } # = in ASDF=1, :- in ${ASDF:-1}
"meta.group.expansion.parameter.shell" = "yellow"        # variables
"variable.other.readwrite"             = "yellow"        # left-hand in assignments
"variable.parameter"                   = "cyan"          # flags

# Expanding bits
# --------------
"keyword.operator.regexp"            = { bold = true, underline = true }  # asterisk in glob, in case...
"meta.group.expansion.history.shell" = { bold = true, underline = true }  # history expansion

# Standouts
# ---------
"constant"               = "blue"  # fd numbers, repeat count
"keyword.operator"       = "blue"  # ||, &&, >, ;, =
"punctuation.terminator" = "blue"  # terminators (e.g. ";;" after a case item)
"support"                = "blue"  # [[, let...

# Paths
# -----
"dynamic.path"              = { bold = true }
"variable.language.tilde"   = { bold = true }

# Utilities
# ---------
"entity.name.function"      = { foreground = "green", underline = true }
"dynamic.callable"          = { foreground = "green" }
"dynamic.callable.alias"    = { foreground = "green", underline = true }
"dynamic.callable.builtin"  = { foreground = "green", bold = true }
"dynamic.callable.command"  = { foreground = "green" }
"dynamic.callable.function" = { foreground = "green", underline = true }
"dynamic.callable.missing"  = { foreground = "red" }
